[BI-111, BI-110, BI-109, BI-108] - BrAPI Germplasm Endpoints
Breeding-Insight/brapi pull request #17
Opened 2020-09-28 15:22 UTC by ctucker3

2020-09-28 20:38 UTC, timparsons requested changes
A few methods with the wrong name, but the structure of the code looks good!  Have a question about the addition of the `geogson-core` library, and if that lines up with the defined BrAPI model.

2020-09-28 20:38 UTC, timparsons commented on brapi-client/src/test/java/org/brapi/client/v2/modules/germplasm/GermplasmAPITests.java
> +        APIException exception = assertThrows(APIException.class, () -> {
Should this test also check the message of the exception to verify it's because of the ID being set when it shouldn't be?

2020-09-28 20:38 UTC, timparsons commented on brapi-client/src/test/java/org/brapi/client/v2/modules/germplasm/GermplasmAPITests.java
> +    public void getProgramByIDSuccess() {
Should this method name be `getGermplasmByIDSuccess`?

2020-09-28 20:38 UTC, timparsons commented on brapi-client/src/test/java/org/brapi/client/v2/modules/germplasm/GermplasmAPITests.java
> +        assertEquals(true, germplasm.isPresent(), "Program was not returned");
I believe the error message is wrong

2020-09-28 20:38 UTC, timparsons commented on brapi-client/src/test/java/org/brapi/client/v2/modules/germplasm/GermplasmAPITests.java
> +    public void getProgramByIdMissingID() {
Method name should be `getGermplasmIdMissingID`

2020-09-28 20:38 UTC, timparsons commented on brapi-client/src/test/java/org/brapi/client/v2/modules/germplasm/GermplasmAPITests.java
> +    public void updateProgramSuccess() {
Method name should be `updateGermplasmSuccess`

2020-09-28 20:38 UTC, timparsons commented on brapi-client/src/test/java/org/brapi/client/v2/modules/germplasm/GermplasmAPITests.java
> +        BrApiGermplasm germplasm = this.germplasm;
Asking for clarification, are you intending for the class-level `germplasm` variable to be updated?

2020-09-28 20:38 UTC, timparsons commented on brapi-client/src/test/java/org/brapi/client/v2/modules/germplasm/GermplasmAPITests.java
> +    public void updateProgramBadId() {
method name should be `updateGermplasmBadId`

2020-09-28 20:38 UTC, timparsons commented on brapi-client/src/test/java/org/brapi/client/v2/modules/germplasm/GermplasmAPITests.java
> +    public void updateProgramMissingId() {
Method name should be `updateGermplasmMissingId`

2020-09-28 20:38 UTC, timparsons commented on brapi-client/src/test/java/org/brapi/client/v2/modules/germplasm/GermplasmAPITests.java
> +                .germplasmName("new test program")
This name should probably be updated

2020-09-28 20:38 UTC, timparsons commented on brapi-core-model/src/main/java/org/brapi/v2/core/model/BrApiGeoJSON.java
> +  private Geometry geometry;
I think this could cause unmarshalling of incoming BrAPI-formatted data to break as the.  Do the models from the added library line up with the geometry models detailed in BrAPI?

2020-09-28 20:38 UTC, timparsons commented on brapi-client/pom.xml
> +        </dependency>
This dependency shouldn't have to be there if it's also been added to `brapi-core-model`

2020-09-28 21:05 UTC, nickpalladino requested changes

2020-09-28 21:05 UTC, nickpalladino commented on brapi-client/src/test/java/org/brapi/client/v2/modules/germplasm/GermplasmAPIUnitTests.java
> +import org.brapi.v2.core.model.BrApiProgram;
unused import

2020-09-28 21:05 UTC, nickpalladino commented on brapi-client/src/test/java/org/brapi/client/v2/modules/germplasm/GermplasmAPITests.java
> +import org.brapi.v2.core.model.BrApiProgram;
unused import

2020-09-28 21:05 UTC, nickpalladino commented on brapi-client/src/test/java/org/brapi/client/v2/modules/germplasm/GermplasmAPITests.java
> +    public void getProgramsSuccess() {
As Tim pointed out, using program terminology instead of germplasm for a lot of these tests, both method names and message strings.

2020-09-29 13:39 UTC, ctucker3 commented on brapi-client/src/main/java/org/brapi/client/v2/modules/germplasm/GermplasmAPI.java
> +        if (germplasmFilter == null) {
Following the pattern set by the programs API. It probably wouldn't be good to change it now since lombok throws a null pointer exception and we throw an illegal argument exception. I don't remember exactly, but perhaps our original motivation to handle it ourselves was so that we could have our own custom error message (or it just wasn't thought of before).

2020-09-29 13:45 UTC, nickpalladino commented on brapi-client/src/main/java/org/brapi/client/v2/modules/germplasm/GermplasmAPI.java
> +        if (germplasmFilter == null) {
Lombok is configured to throw an IllegalArgumentException, it's what I was using for the variables stuff. The programs API was earlier on so I think some of the patterns changed after that, not sure about the error message.

2020-09-29 13:51 UTC, nickpalladino commented on brapi-germplasm-model/src/main/java/org/brapi/v2/germplasm/model/BrApiBiologicalStatusOfAccessionCode.java
> +    _100("100", "Wild"),
Why start with an underscore?

2020-09-29 13:54 UTC, ctucker3 commented on brapi-core-model/src/main/java/org/brapi/v2/core/model/BrApiGeoJSON.java
> +  private Geometry geometry;
It should work the same. In the brapi documentation the `geometry` holds a GeoJson object. So that object isn't brapi specific. I used this because the brapi models were broken for geometry reading and gson required custom typing conversion work to get them to work. It looked like quite an undertaking to do that work, which is why I went with this method to keep the feature in the timeline. I can check out the fixes that Pete put in though if we wanted our geometry classes to be named like 'BrAPIGeomtry' instead of this libraries class naming?

2020-09-29 14:12 UTC, ctucker3 commented on brapi-client/src/test/java/org/brapi/client/v2/modules/germplasm/GermplasmAPITests.java
> +        APIException exception = assertThrows(APIException.class, () -> {
Sounds like a good thing to check. Add it to the update endpoint test as well.

2020-09-29 14:12 UTC, ctucker3 commented on brapi-client/src/test/java/org/brapi/client/v2/modules/germplasm/GermplasmAPITests.java
> +    public void getProgramByIDSuccess() {
Changed and pushed

2020-09-29 14:13 UTC, ctucker3 commented on brapi-client/src/test/java/org/brapi/client/v2/modules/germplasm/GermplasmAPITests.java
> +        assertEquals(true, germplasm.isPresent(), "Program was not returned");
Changed and pushed

2020-09-29 14:14 UTC, ctucker3 commented on brapi-client/src/test/java/org/brapi/client/v2/modules/germplasm/GermplasmAPITests.java
> +    public void getProgramByIdMissingID() {
Changed and pushed

2020-09-29 14:15 UTC, ctucker3 commented on brapi-client/src/test/java/org/brapi/client/v2/modules/germplasm/GermplasmAPITests.java
> +    public void updateProgramSuccess() {
Changed and pushed

2020-09-29 14:16 UTC, ctucker3 commented on brapi-client/src/test/java/org/brapi/client/v2/modules/germplasm/GermplasmAPITests.java
> +    public void updateProgramBadId() {
Changed and pushed

2020-09-29 14:16 UTC, ctucker3 commented on brapi-client/src/test/java/org/brapi/client/v2/modules/germplasm/GermplasmAPITests.java
> +    public void updateProgramMissingId() {
Changed and pushed

2020-09-29 14:16 UTC, ctucker3 commented on brapi-client/src/test/java/org/brapi/client/v2/modules/germplasm/GermplasmAPITests.java
> +                .germplasmName("new test program")
Changed and pushed

2020-09-29 14:17 UTC, ctucker3 commented on brapi-client/pom.xml
> +        </dependency>
Good catch, removed

2020-09-29 14:17 UTC, ctucker3 commented on brapi-client/src/main/java/org/brapi/client/v2/modules/germplasm/GermplasmAPI.java
> +package org.brapi.client.v2.modules.germplasm;
Added headers on all the new files

2020-09-29 14:17 UTC, ctucker3 commented on brapi-client/src/main/java/org/brapi/client/v2/modules/germplasm/GermplasmAPI.java
> +import org.brapi.v2.core.model.BrApiProgram;
Remove all unused imports

2020-09-29 14:25 UTC, ctucker3 commented on brapi-client/src/main/java/org/brapi/client/v2/modules/germplasm/GermplasmAPI.java
> +        if (germplasmFilter == null) {
Oh yep, I see now that it can be configured. Thanks for sticking to this! Changed and pushed

2020-09-29 14:27 UTC, ctucker3 commented on brapi-client/src/test/java/org/brapi/client/v2/modules/germplasm/GermplasmAPITests.java
> +package org.brapi.client.v2.modules.germplasm;
Added headers on all the new files

2020-09-29 14:27 UTC, ctucker3 commented on brapi-client/src/test/java/org/brapi/client/v2/modules/germplasm/GermplasmAPIUnitTests.java
> +package org.brapi.client.v2.modules.germplasm;
Added headers on all the new files

2020-09-29 14:27 UTC, ctucker3 commented on brapi-client/src/test/java/org/brapi/client/v2/modules/germplasm/GermplasmAPIUnitTests.java
> +import org.brapi.v2.core.model.BrApiProgram;
Removed

2020-09-29 14:27 UTC, ctucker3 commented on brapi-client/src/test/java/org/brapi/client/v2/modules/germplasm/GermplasmAPITests.java
> +import org.brapi.v2.core.model.BrApiProgram;
Removed

2020-09-29 14:27 UTC, ctucker3 commented on brapi-client/src/test/java/org/brapi/client/v2/modules/germplasm/GermplasmAPITests.java
> +    public void getProgramsSuccess() {
Don't blame me, blame Ctrl + V. Changed and pushed

2020-09-29 14:31 UTC, ctucker3 commented on brapi-germplasm-model/src/main/java/org/brapi/v2/germplasm/model/BrApiBiologicalStatusOfAccessionCode.java
> +    _100("100", "Wild"),
It doesn't like when you start identifiers with numbers, you have to start with a non-number character..

2020-09-29 16:40 UTC, timparsons commented on brapi-core-model/src/main/java/org/brapi/v2/core/model/BrApiGeoJSON.java
> +  private Geometry geometry;
Ok, that sounds fine to me.  I just wanted to make sure :) Thanks!

2020-09-29 16:47 UTC, timparsons commented on brapi-germplasm-model/src/main/java/org/brapi/v2/germplasm/model/BrApiBiologicalStatusOfAccessionCode.java
> +    _100("100", "Wild"),
What about having the identifiers being named after the `description` field?  For example, `_100` would change to `WILD`, and `_120` would change to `SEMI_NATURAL_OR_WILD`

2020-09-29 16:48 UTC, timparsons commented on brapi-germplasm-model/src/main/java/org/brapi/v2/germplasm/model/BrApiGermplasmStorageTypeCode.java
> +    _10("10", "Seed collection"),
similar to above (https://github.com/Breeding-Insight/brapi/pull/17/files/1da907bf9adf1b98576a91ac52bc32f0ee77d6a8#r496889304), the identifiers could be renamed to reflect the `description` field: `_10` -> `SEED_COLLECTION`

2020-09-29 17:39 UTC, ctucker3 commented on brapi-client/src/test/java/org/brapi/client/v2/modules/germplasm/GermplasmAPITests.java
> +        BrApiGermplasm germplasm = this.germplasm;
Updated and pushed

2020-09-29 17:47 UTC, ctucker3 commented on brapi-germplasm-model/src/main/java/org/brapi/v2/germplasm/model/BrApiBiologicalStatusOfAccessionCode.java
> +    _100("100", "Wild"),
Yep, I think that makes sense. Let me try it out.

2020-09-29 18:48 UTC, nickpalladino approved these changes

2020-09-29 18:48 UTC, nickpalladino commented on brapi-client/src/main/java/org/brapi/client/v2/modules/germplasm/GermplasmAPI.java
> +    public Optional<BrApiGermplasm> createGermplasm(BrApiGermplasm brApiGermplasm) throws HttpException, APIException {
Should you also add @Nonnull here

2020-09-29 18:48 UTC, nickpalladino commented on brapi-client/src/main/java/org/brapi/client/v2/modules/germplasm/GermplasmAPI.java
> +    public Optional<BrApiGermplasm> updateGermplasm(BrApiGermplasm brApiGermplasm) throws HttpException, APIException {
Should you also add @Nonnull here

2020-09-29 19:29 UTC, timparsons approved these changes

2020-10-01 12:11 UTC, merged